[input]
    read1 = 'input.fq'

[barcodes.cells]
    AAAA = "cell_A"
    TTTT = "cell_T"

[barcodes.genes]
    CCCC = "gene_C"
    GGGG = "gene_G"

[[step]]
    action = "ExtractRegion"
    source = "read1"
    anchor = "start"
    start = 0
    length = 4
    out_label = "cell_bc"

[[step]]
    action = "ExtractRegion"
    source = "read1"
    anchor = "start"
    start = 4
    length = 4
    out_label = "gene_bc"

[[step]]
    action = "ExtractRegex"
    source = "read1"
    query = "T[ACGT]{3}$"
    out_label = "umi"

[[step]]
    action = "StoreSingleCellMatrix"
    cell_tag = "cell_bc"
    gene_tag = "gene_bc"
    umi_tag = "umi"
    cell_barcodes = "cells"
    gene_barcodes = "genes"
    umi_aggregation = 'None'

[output]
    prefix = "output"
