[package]
name = "fastqrab-dna"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Low-level DNA primitives for fastqrab: sequence/quality handling, segments, and approximate matching"
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[dependencies]
    anyhow = {workspace = true}
	bio = {workspace = true}
	bstr = {workspace = true}
    hamming-resonate = {workspace = true}
    indexmap = {workspace = true}
	schemars = {workspace = true}
	toml-pretty-deser = {workspace = true}
	smallvec = {workspace = true}
    stringpod = {workspace = true}
	triple_accel = {workspace = true}

[lints]
workspace = true
