# We used to 'shut down' the input when a head was 'full',
# but we must not do that if a Report/Quantify/Inspect was before


[input]
    read1 = 'input_read1.fq.zst'
    read2 = 'input_read2.fq.zst'
[options]
    block_size = 15

[[step]]
    action = 'ExtractRegions'
    out_label = 'kmer1'

    regions = [
            {  start = 6, length = 6, anchor="Start"},
    ]
    segment = 'read1'

[[step]]
    action = 'ExtractRegions'
    out_label = 'kmer2'

    regions = [
            {  start = 10, length = 7, anchor="Start"}
    ]
    segment = 'read2'

[[step]]
  action= 'ConcatTags'
  in_labels = ['kmer1', 'kmer2']
  out_label = 'kmer'
  on_missing = 'SetMissing'
  separator = 'xyz'

[[step]]
    action = 'QuantifyTag'
    infix = 'kmer'
    in_label = 'kmer'
    # region_separator = 'xyz'

[[step]]
    action ='Head'
    n = 10

[output]
    prefix = 'output'

