#!/usr/bin/env python3

from pathlib import Path
import shutil
import subprocess

assert Path("cookbooks").exists(), "Starting from the wrong dir, cookbooks not found"


def run_cookbook(dir):
    print(f"Processing cookbook in {dir}")
    files_before = set(dir.iterdir())
    subprocess.check_call(
        [
            "cargo",
            "run",
            "--release",
            "--",
            "process",
            "input.toml",
            ".",
            "--allow-overwrite",
        ],
        cwd=dir,
    )
    ref_output = dir / "reference_output"
    if ref_output.exists():
        shutil.rmtree(ref_output)
    files_after = set(dir.iterdir())
    ref_output.mkdir()
    for new_file in files_after - files_before:
        if new_file.name.startswith("output"):
            shutil.move(str(new_file), ref_output / new_file.name)


# Find all cookbook directories (those with input.toml)
cookbooks = []
for input_toml in sorted(Path("cookbooks").rglob("input.toml")):
    cookbook_dir = Path(input_toml.parent)
    # Skip test output directories
    if "reference_output" in str(cookbook_dir) or "actual" in str(cookbook_dir):
        continue

    # Get the cookbook number and name
    cookbook_name = cookbook_dir.name
    cookbook_path = str(cookbook_dir.relative_to("cookbooks"))

    # Read README.md if it exists
    readme_path = cookbook_dir / "README.md"
    readme_content = ""
    if readme_path.exists():
        readme_content = readme_path.read_text()

    # Read input.toml
    toml_content = input_toml.read_text()

    run_cookbook(cookbook_dir)
    # that's done by the doc generation actually.

    cookbooks.append(
        {
            "name": cookbook_name,
            "path": cookbook_path,
            "readme": readme_content,
            "toml": toml_content,
        }
    )

# Generate Rust code
out = """// This file is auto-generated by dev/_update_cookbooks.py
// Do not edit manually - changes will be overwritten

pub struct Cookbook {
    pub number: usize,
    pub name: &'static str,
    pub readme: &'static str,
    pub toml: &'static str,
}

"""

# Add the cookbooks array
out += "pub const COOKBOOKS: &[Cookbook] = &[\n"
for i, cb in enumerate(cookbooks, 1):
    name_escaped = cb["name"].replace('"', '\\"')

    out += f'''    Cookbook {{
        number: {i},
        name: "{name_escaped}",
        readme: include_str!("../cookbooks/{cb["path"]}/README.md"),
        toml: include_str!("../cookbooks/{cb["path"]}/input.toml"),
    }},
'''

out += "];\n"

# Add helper functions
out += """
/// Get all cookbook names and their paths
pub fn list_cookbooks() -> Vec<(usize, &'static str)> {
    COOKBOOKS.iter()
        .map(|cb| (cb.number, cb.name))
        .collect()
}

/// Get a specific cookbook by number (1-indexed)
pub fn get_cookbook(number: usize) -> Option<&'static Cookbook> {
    COOKBOOKS.iter().find(|cb| cb.number == number)
}

/// Get the total number of cookbooks
pub fn cookbook_count() -> usize {
    COOKBOOKS.len()
}
"""

out_path = Path("src/cookbooks.rs")
out_path.write_text(out)

subprocess.check_call(["cargo", "fmt", "--", str(out_path)])

print(f"Generated cookbook data for {len(cookbooks)} cookbooks")
