[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegex'
    source = 'read1'
    out_label = 'region'
    query = '^AC'


[[step]]
  action = 'ExtractRegion'
  source = 'read1'
  start = 0
  len = 0
  anchor = 'left'
  out_label = 'empty_region'

[[step]]
    action = 'CalcWorstQuality'
    out_label = 'worst_q'
    source = 'tag:region'
    offset = -34

[[step]]
    action = 'CalcWorstQuality'
    out_label = 'worst_q_empty'
    source = 'tag:empty_region'
    offset = -34

[output]
    prefix = "output"

[[step]]
action = 'Outputtable'
