#&!/usr/bin/env python3

from pathlib import Path
import shutil
import subprocess
import sys

assert Path("cookbooks").exists(), "Starting from the wrong dir, cookbooks not found"

# Find all cookbook directories (those with input.toml)
cookbooks = []
for input_toml in sorted(Path("cookbooks").rglob("input.toml")):
    cookbook_dir = Path(input_toml.parent)
    # Skip test output directories
    if "reference_output" in str(cookbook_dir) or "actual" in str(cookbook_dir):
        continue

    # Get the cookbook number and name
    cookbook_name = cookbook_dir.name
    cookbook_path = str(cookbook_dir.relative_to("cookbooks"))

    # Read README.md if it exists
    readme_path = cookbook_dir / "README.md"
    readme_content = ""
    if readme_path.exists():
        readme_content = readme_path.read_text()

    # Read input.toml
    toml_content = input_toml.read_text()

    # that's done by the doc generation actually.

    cookbooks.append(
        {
            "name": cookbook_name,
            "path": cookbook_path,
            "readme": readme_content,
            "toml": toml_content,
        }
    )

def rust_raw_str(content: str) -> str:
    """Wrap content in a Rust raw string literal with enough # delimiters."""
    hashes = 0
    while f'"{("#" * hashes)}' in content:
        hashes += 1
    delim = "#" * hashes
    return f'r{delim}"{content}"{delim}'


# Generate Rust code
out = """// This file is auto-generated by dev/_update_cookbooks.py
// Do not edit manually - changes will be overwritten
// Strings are inlined (not include_str!) so `cargo publish` works without
// bundling files from outside the crate directory.

pub struct Cookbook {
    pub number: usize,
    pub name: &'static str,
    pub readme: &'static str,
    pub toml: &'static str,
}

"""

# Add the cookbooks array
out += "pub const COOKBOOKS: &[Cookbook] = &[\n"
for i, cb in enumerate(cookbooks, 1):
    name_escaped = cb["name"].replace('"', '\\"')
    readme_lit = rust_raw_str(cb["readme"])
    toml_lit = rust_raw_str(cb["toml"])

    out += f'''    Cookbook {{
        number: {i},
        name: "{name_escaped}",
        readme: {readme_lit},
        toml: {toml_lit},
    }},
'''

out += "];\n"

# Add helper functions
out += """
/// Get all cookbook names and their paths
#[must_use]
pub fn list_cookbooks() -> Vec<(usize, &'static str)> {
    COOKBOOKS.iter()
        .map(|cb| (cb.number, cb.name))
        .collect()
}

/// Get a specific cookbook by number (1-indexed)
#[must_use]
pub fn get_cookbook(number: usize) -> Option<&'static Cookbook> {
    COOKBOOKS.iter().find(|cb| cb.number == number)
}

/// Get a specific cookbook by name
#[must_use]
pub fn get_cookbook_by_name(name: &str) -> Option<&'static Cookbook> {
    COOKBOOKS.iter().find(|cb| cb.name == name)
}

"""

out_path = Path("fastqrab/src/cookbooks.rs")
out_path.write_text(out)

subprocess.check_call(["cargo", "fmt", "--", str(out_path)])

print(f"Generated cookbook data for {len(cookbooks)} cookbooks")
