[input]
  read1 ="input_read1.fq"


[[step]]
  action ="ExtractRegion"
  out_label = "reg1"
  start = 0
  length = 3 
anchor = "lefT"
source = 'read1'

[[step]]
  action ="CalcLength"
  out_label ="len1"


[[step]]
  action ="Skip"
  n = 3


[[step]]
  action = "StoreTagsInTable"

[output]
  prefix = "out"
