[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read1.fq'
    read3 = 'input_read1.fq'
    read4 = 'input_read1.fq'
    read5 = 'input_read1.fq'
    read6 = 'input_read1.fq'
    read7 = 'input_read1.fq'
    read8 = 'input_read1.fq'
    read9 = 'input_read1.fq'
    read10 = 'input_read1.fq'
    read11 = 'input_read1.fq'
    read12 = 'input_read1.fq'
    read13 = 'input_read1.fq'
    read14 = 'input_read1.fq'
    read15 = 'input_read1.fq'
    read16 = 'input_read1.fq'
    read17 = 'input_read1.fq'
    read18 = 'input_read1.fq'
    read19 = 'input_read1.fq'
    read20 = 'input_read1.fq'
    read21 = 'input_read1.fq'
    read22 = 'input_read1.fq'
    read23 = 'input_read1.fq'
    read24 = 'input_read1.fq'
    read25 = 'input_read1.fq'
    read26 = 'input_read1.fq'
    read27 = 'input_read1.fq'
    read28 = 'input_read1.fq'
    read29 = 'input_read1.fq'
    read30 = 'input_read1.fq'
    read31 = 'input_read1.fq'
    read32 = 'input_read1.fq'
    read33 = 'input_read1.fq'
    read34 = 'input_read1.fq'
    read35 = 'input_read1.fq'
    read36 = 'input_read1.fq'
    read37 = 'input_read1.fq'
    read38 = 'input_read1.fq'
    read39 = 'input_read1.fq'
    read40 = 'input_read1.fq'
    read41 = 'input_read1.fq'
    read42 = 'input_read1.fq'
    read43 = 'input_read1.fq'
    read44 = 'input_read1.fq'
    read45 = 'input_read1.fq'
    read46 = 'input_read1.fq'
    read47 = 'input_read1.fq'
    read48 = 'input_read1.fq'
    read49 = 'input_read1.fq'
    read50 = 'input_read1.fq'
    read51 = 'input_read1.fq'
    read52 = 'input_read1.fq'
    read53 = 'input_read1.fq'
    read54 = 'input_read1.fq'
    read55 = 'input_read1.fq'
    read56 = 'input_read1.fq'
    read57 = 'input_read1.fq'
    read58 = 'input_read1.fq'
    read59 = 'input_read1.fq'
    read60 = 'input_read1.fq'
    read61 = 'input_read1.fq'
    read62 = 'input_read1.fq'
    read63 = 'input_read1.fq'
    read64 = 'input_read1.fq'
    read65 = 'input_read1.fq'
    read66 = 'input_read1.fq'
    read67 = 'input_read1.fq'
    read68 = 'input_read1.fq'
    read69 = 'input_read1.fq'
    read70 = 'input_read1.fq'
    read71 = 'input_read1.fq'
    read72 = 'input_read1.fq'
    read73 = 'input_read1.fq'
    read74 = 'input_read1.fq'
    read75 = 'input_read1.fq'
    read76 = 'input_read1.fq'
    read77 = 'input_read1.fq'
    read78 = 'input_read1.fq'
    read79 = 'input_read1.fq'
    read80 = 'input_read1.fq'
    read81 = 'input_read1.fq'
    read82 = 'input_read1.fq'
    read83 = 'input_read1.fq'
    read84 = 'input_read1.fq'
    read85 = 'input_read1.fq'
    read86 = 'input_read1.fq'
    read87 = 'input_read1.fq'
    read88 = 'input_read1.fq'
    read89 = 'input_read1.fq'
    read90 = 'input_read1.fq'
    read91 = 'input_read1.fq'
    read92 = 'input_read1.fq'
    read93 = 'input_read1.fq'
    read94 = 'input_read1.fq'
    read95 = 'input_read1.fq'
    read96 = 'input_read1.fq'
    read97 = 'input_read1.fq'
    read98 = 'input_read1.fq'
    read99 = 'input_read1.fq'
    read100 = 'input_read1.fq'
    read101 = 'input_read1.fq'
    read102 = 'input_read1.fq'
    read103 = 'input_read1.fq'
    read104 = 'input_read1.fq'
    read105 = 'input_read1.fq'
    read106 = 'input_read1.fq'
    read107 = 'input_read1.fq'
    read108 = 'input_read1.fq'
    read109 = 'input_read1.fq'
    read110 = 'input_read1.fq'
    read111 = 'input_read1.fq'
    read112 = 'input_read1.fq'
    read113 = 'input_read1.fq'
    read114 = 'input_read1.fq'
    read115 = 'input_read1.fq'
    read116 = 'input_read1.fq'
    read117 = 'input_read1.fq'
    read118 = 'input_read1.fq'
    read119 = 'input_read1.fq'
    read120 = 'input_read1.fq'
    read121 = 'input_read1.fq'
    read122 = 'input_read1.fq'
    read123 = 'input_read1.fq'
    read124 = 'input_read1.fq'
    read125 = 'input_read1.fq'
    read126 = 'input_read1.fq'
    read127 = 'input_read1.fq'
    read128 = 'input_read1.fq'
    read129 = 'input_read1.fq'
    read130 = 'input_read1.fq'
    read131 = 'input_read1.fq'
    read132 = 'input_read1.fq'
    read133 = 'input_read1.fq'
    read134 = 'input_read1.fq'
    read135 = 'input_read1.fq'
    read136 = 'input_read1.fq'
    read137 = 'input_read1.fq'
    read138 = 'input_read1.fq'
    read139 = 'input_read1.fq'
    read140 = 'input_read1.fq'
    read141 = 'input_read1.fq'
    read142 = 'input_read1.fq'
    read143 = 'input_read1.fq'
    read144 = 'input_read1.fq'
    read145 = 'input_read1.fq'
    read146 = 'input_read1.fq'
    read147 = 'input_read1.fq'
    read148 = 'input_read1.fq'
    read149 = 'input_read1.fq'
    read150 = 'input_read1.fq'
    read151 = 'input_read1.fq'
    read152 = 'input_read1.fq'
    read153 = 'input_read1.fq'
    read154 = 'input_read1.fq'
    read155 = 'input_read1.fq'
    read156 = 'input_read1.fq'
    read157 = 'input_read1.fq'
    read158 = 'input_read1.fq'
    read159 = 'input_read1.fq'
    read160 = 'input_read1.fq'
    read161 = 'input_read1.fq'
    read162 = 'input_read1.fq'
    read163 = 'input_read1.fq'
    read164 = 'input_read1.fq'
    read165 = 'input_read1.fq'
    read166 = 'input_read1.fq'
    read167 = 'input_read1.fq'
    read168 = 'input_read1.fq'
    read169 = 'input_read1.fq'
    read170 = 'input_read1.fq'
    read171 = 'input_read1.fq'
    read172 = 'input_read1.fq'
    read173 = 'input_read1.fq'
    read174 = 'input_read1.fq'
    read175 = 'input_read1.fq'
    read176 = 'input_read1.fq'
    read177 = 'input_read1.fq'
    read178 = 'input_read1.fq'
    read179 = 'input_read1.fq'
    read180 = 'input_read1.fq'
    read181 = 'input_read1.fq'
    read182 = 'input_read1.fq'
    read183 = 'input_read1.fq'
    read184 = 'input_read1.fq'
    read185 = 'input_read1.fq'
    read186 = 'input_read1.fq'
    read187 = 'input_read1.fq'
    read188 = 'input_read1.fq'
    read189 = 'input_read1.fq'
    read190 = 'input_read1.fq'
    read191 = 'input_read1.fq'
    read192 = 'input_read1.fq'
    read193 = 'input_read1.fq'
    read194 = 'input_read1.fq'
    read195 = 'input_read1.fq'
    read196 = 'input_read1.fq'
    read197 = 'input_read1.fq'
    read198 = 'input_read1.fq'
    read199 = 'input_read1.fq'
    read200 = 'input_read1.fq'
    read201 = 'input_read1.fq'
    read202 = 'input_read1.fq'
    read203 = 'input_read1.fq'
    read204 = 'input_read1.fq'
    read205 = 'input_read1.fq'
    read206 = 'input_read1.fq'
    read207 = 'input_read1.fq'
    read208 = 'input_read1.fq'
    read209 = 'input_read1.fq'
    read210 = 'input_read1.fq'
    read211 = 'input_read1.fq'
    read212 = 'input_read1.fq'
    read213 = 'input_read1.fq'
    read214 = 'input_read1.fq'
    read215 = 'input_read1.fq'
    read216 = 'input_read1.fq'
    read217 = 'input_read1.fq'
    read218 = 'input_read1.fq'
    read219 = 'input_read1.fq'
    read220 = 'input_read1.fq'
    read221 = 'input_read1.fq'
    read222 = 'input_read1.fq'
    read223 = 'input_read1.fq'
    read224 = 'input_read1.fq'
    read225 = 'input_read1.fq'
    read226 = 'input_read1.fq'
    read227 = 'input_read1.fq'
    read228 = 'input_read1.fq'
    read229 = 'input_read1.fq'
    read230 = 'input_read1.fq'
    read231 = 'input_read1.fq'
    read232 = 'input_read1.fq'
    read233 = 'input_read1.fq'
    read234 = 'input_read1.fq'
    read235 = 'input_read1.fq'
    read236 = 'input_read1.fq'
    read237 = 'input_read1.fq'
    read238 = 'input_read1.fq'
    read239 = 'input_read1.fq'
    read240 = 'input_read1.fq'
    read241 = 'input_read1.fq'
    read242 = 'input_read1.fq'
    read243 = 'input_read1.fq'
    read244 = 'input_read1.fq'
    read245 = 'input_read1.fq'
    read246 = 'input_read1.fq'
    read247 = 'input_read1.fq'
    read248 = 'input_read1.fq'
    read249 = 'input_read1.fq'
    read250 = 'input_read1.fq'
    read251 = 'input_read1.fq'
    read252 = 'input_read1.fq'
    read253 = 'input_read1.fq'
    read254 = 'input_read1.fq'
    read255 = 'input_read1.fq'
    read256 = 'input_read1.fq'
    read257 = 'input_read1.fq'

[options]
  accept_duplicate_files=true

[output]
    prefix = "output"

[[step]]
    action = "OutputFASTQ"
