// Module declarations
pub mod cut_start;
pub mod cut_end;
pub mod max_len;
pub mod prefix;
pub mod postfix;
pub mod reverse_complement;
pub mod phred64_to33;
pub mod rename;
pub mod trim_quality_start;
pub mod trim_quality_end;
pub mod swap_r1_and_r2;
pub mod lowercase_tag;
pub mod uppercase_tag;
pub mod lowercase_sequence;
pub mod uppercase_sequence;

// Re-exports
pub use cut_start::CutStart;
pub use cut_end::CutEnd;
pub use max_len::MaxLen;
pub use prefix::Prefix;
pub use postfix::Postfix;
pub use reverse_complement::ReverseComplement;
pub use phred64_to33::Phred64To33;
pub use rename::Rename;
pub use trim_quality_start::TrimQualityStart;
pub use trim_quality_end::TrimQualityEnd;
pub use swap_r1_and_r2::SwapR1AndR2;
pub use lowercase_tag::LowercaseTag;
pub use uppercase_tag::UppercaseTag;
pub use lowercase_sequence::LowercaseSequence;
pub use uppercase_sequence::UppercaseSequence;