[input]
  read1 = 'input_read1.fq'


[[step]]
  action = "ExtractRegex"
  source = 'read1'
  query = 'A+'
  out_label = 'polyA'

[[step]]
  action = 'StoreTagsInTable'
  in_labels = ['polyA', 'location_polyX']

[output]
    prefix = "output"
