cp demultiplex/simple_demultiplex_basics/output.json demultiplex/simple_demultiplex_basics/output.json

cp demultiplex/simple_demultiplex_single_barcode_no_unmatched_output/actual/output.json demultiplex/simple_demultiplex_single_barcode_no_unmatched_output/output.json

cp head_early_termination/head_after_report/actual/output.json head_early_termination/head_after_report/output.json

cp head_early_termination/head_before_report/actual/output.json head_early_termination/head_before_report/output.json

cp head_early_termination/multi_stage_head/actual/output.json head_early_termination/multi_stage_head/output.json

cp head_early_termination/multi_stage_head_report_bottom/actual/output.json head_early_termination/multi_stage_head_report_bottom/output.json

cp head_early_termination/multi_stage_head_report_middle/actual/output.json head_early_termination/multi_stage_head_report_middle/output.json

cp head_early_termination/multi_stage_head_report_middle_bottom/actual/output.json head_early_termination/multi_stage_head_report_middle_bottom/output.json

cp head_early_termination/multi_stage_head_report_top/actual/output.json head_early_termination/multi_stage_head_report_top/output.json

cp integration_tests/gzip_blocks_spliting_reads/actual/output.json integration_tests/gzip_blocks_spliting_reads/output.json

cp reports/duplication_count_is_stable/actual/output.json reports/duplication_count_is_stable/output.json

cp reports/oligo_counts/actual/output.json reports/oligo_counts/output.json

cp reports/oligo_counts_2/actual/output.json reports/oligo_counts_2/output.json

cp reports/read_length_reporting/actual/output.json reports/read_length_reporting/output.json

cp reports/report/actual/output.json reports/report/output.json

cp reports/report_depduplication_per_fragment/actual/output.json reports/report_depduplication_per_fragment/output.json

cp reports/report_no_output/actual/output.json reports/report_no_output/output.json

cp reports/report_ordering/actual/output.json reports/report_ordering/output.json

cp reports/report_pe/actual/output.json reports/report_pe/actual/output.json
