[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegions'
    regions = [
      {start= 0, length= 6, anchor= 'left'},
      {start= 2, length= 2, anchor= 'left'},
]
    source = 'read1'
    out_label = 'tag1'

[[step]]
    action = 'ConcatTags'
    in_labels = ['tag1']
    out_label = 'combined'
    on_missing = 'merge_present'
    separator = "-"

[[step]]
  action = 'StoreTagsInTable'
[output]
    prefix = 'output'
    format = 'none'
