// This file is auto-generated by dev/_update_cookbooks.py
// Do not edit manually - changes will be overwritten
// Strings are inlined (not include_str!) so `cargo publish` works without
// bundling files from outside the crate directory.

pub struct Cookbook {
    pub number: usize,
    pub name: &'static str,
    pub readme: &'static str,
    pub toml: &'static str,
}

pub const COOKBOOKS: &[Cookbook] = &[
    Cookbook {
        number: 1,
        name: "01-basic-quality-report",
        readme: r"# Cookbook 01: Basic Quality Report

## Use Case

You have FastQ files from a sequencing run and want to generate comprehensive quality reports to assess:
- Read quality scores
- Base composition
- Read length distribution
- Duplicate read counts

This is typically the first step in any sequencing data analysis to understand data quality before downstream processing.

## What This Pipeline Does

1. Reads input FastQ file(s)
2. Generates a comprehensive quality report including:
   - Base quality statistics
   - Base distribution across positions
   - Read length distribution
   - Duplicate read counting
3. Outputs reports in both HTML (human-readable) and JSON (machine-readable) formats
4. Passes through all reads unchanged (no filtering)

## Input Files

- `input/sample_R1.fq` - Forward reads (Read 1) from paired-end sequencing

## Output Files

- `output_R1.fq` - Passed-through reads (identical to input)
- `output.report_initial.html` - HTML quality report
- `output.report_initial.json` - JSON quality report with detailed statistics

## When to Use This

- First analysis of new sequencing data
- Quality control before committing to expensive downstream analysis
- Comparing data quality across different sequencing runs
- Identifying potential issues (adapter contamination, quality drop-off, etc.)

",
        toml: r#"[input]
    # Single-end reads for this example
    # For paired-end data, you would also include: read2 = 'input/sample_R2.fq'
    read1 = 'input/sample_R1.fq'

[[step]]
  action = "CalcGCContent"
    relative = true
  out_label = "gc_content"

[[step]]
    # Generate a comprehensive quality report
    action = 'Report'
    name = 'initial'

    # Count total number of reads
    count = true

    # Analyze base quality scores and GC content
    base_statistics = true
    # Analyze the distribution of read lengths

    length_distribution = true

    # Count duplicate reads (identical sequences)
    duplicate_count_per_read = true

    # Count duplicate reads (identical sequences)
    duplicate_count_per_fragment = true

    # count how often these oligos occur.
    # no mismatches, no IUPAC
	count_oligos = {AAAAAA = 'AAAAAA', p5_adapter = 'GATCGGAAGAGCACACGTCTGAACTCCAGTCAC', p7_adapter = 'ATCTCGTATGCCGTCTTCTGCTTG', GGGGGGGGGGG = 'GGGGGGGGGGG'}

    # Histogram of gc content (rounded to nearest integer)
  # optional
    tag_histograms = ["gc_content"]


[output]
    prefix = "reference_output/output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"

[[step]]
    action = "OutputReport"
    json = true
    html = true
"#,
    },
    Cookbook {
        number: 2,
        name: "02-umi-extraction",
        readme: r#"# Cookbook 02: UMI Extraction

## Use Case

You have sequencing data with Unique Molecular Identifiers (UMIs) embedded in the reads. UMIs are short random barcodes added during library preparation that allow you to:
- Identify and remove PCR duplicates
- Distinguish true biological duplicates from amplification artifacts
- Improve accuracy in quantitative analyses (RNA-seq, ATAC-seq, etc.)

## What This Pipeline Does

1. Reads input FastQ file with UMIs at the start of read1
2. Extracts the UMI sequence (first 8 bases) and creates a tag
3. Stores the UMI in the read comment (FASTQ header)
4. Removes the UMI bases from the read sequence (so they don't interfere with alignment)
5. Outputs modified reads with UMI preserved in the header

## Input Files

- `input/sample_R1.fq` - Reads with 8bp UMI at the start

## Output Files

- `output_R1.fq` - Reads with UMI in comment, UMI bases removed from sequence

## Configuration Highlights

```toml
[[step]]
    # Extract UMI from positions 0-7 (8 bases)
    action = 'ExtractRegions'
    label = 'umi'
    regions = [{source = 'read1', start = 0, length = 8, anchor="Start"}]

[[step]]
    # Store UMI in the FASTQ comment
    action = 'StoreTagInComment'
    label = 'umi'

[[step]]
    # Remove the UMI bases from the read
    action = 'CutStart'
    target = 'Read1'
    n = 8
```

## Workflow Details

**Before processing:**
```
@READ1
ATCGATCGACTGTACTGTACTGTACTGTACTG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
```

**After processing:**
```
@READ1|umi=ATCGATCG
ACTGTACTGTACTGTACTGTACTG
+
IIIIIIIIIIIIIIIIIIIIIIII
```

The UMI `ATCGATCG` is now in the comment and removed from the sequence.

## When to Use This

- Single-cell RNA-seq with UMIs
- ATAC-seq with UMI-based deduplication
- Any protocol using unique molecular identifiers
- Before alignment when you need to preserve UMIs for downstream duplicate marking

"#,
        toml: r#"[input]
    read1 = 'input/sample_R1.fq'

[[step]]
    # Extract UMI from the first 8 bases of read1
    action = 'ExtractRegions'
    out_label = 'umi'
    regions = [{ start = 0, length = 8, anchor="Start"}]
    source = 'read1'

[[step]]
    # Store the UMI tag in the FASTQ comment
    # This preserves it through alignment and enables UMI-aware deduplication
    action = 'StoreTagInComment'
    in_label = 'umi'

[[step]]
    # Remove the UMI bases from the read sequence
    # Important: Do this AFTER storing the UMI in the comment
    action = 'CutStart'
    segment = 'read1'
    n = 8

[output]
    prefix = "reference_output/cookbook-02"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"
"#,
    },
    Cookbook {
        number: 3,
        name: "03-lexogen-quantseq",
        readme: r"# Cookbook 03: Lexogen QuantSeq Processing

## Use Case

Lexogen QuantSeq is a popular 3' mRNA sequencing protocol optimized for gene expression profiling. The library structure includes:
- **First 8 bases**: UMI (Unique Molecular Identifier) for deduplication
- **Next 6 bases**: Random hexamer primer sequence (needs removal)
- **Remaining sequence**: Actual cDNA from the 3' end of transcripts

This cookbook demonstrates the standard preprocessing for QuantSeq data before alignment.

## What This Pipeline Does

1. Extracts the 8bp UMI from the start of reads
2. Stores the UMI in the read comment (FASTQ header)
3. Removes the first 14 bases total (8bp UMI + 6bp random hexamer)
4. Outputs processed reads ready for alignment

## Input Files

- `input/quantseq_sample.fq` - Raw QuantSeq reads with UMI and random hexamer

## Output Files

- `output_read1.fq` - Processed reads with:
  - UMI stored in comment
  - First 14bp removed
  - Ready for alignment to reference genome

## Workflow Details

**Raw read structure:**
```
@READ1
ATCGATCGTTACGATACTGTACTGTACTGTAC...
^^^^^^  UMI <- These get removed
      ^^^^ Hexamer  <- These get removed
          ^^^^^^^^^^^^^^^^^^^^^^... <- This stays for alignment
```

**After processing:**
```
@READ1 umi:ATCGATCG
ACTGTACTGTACTGTAC...
```

The UMI is preserved in the comment for downstream deduplication, and the adapter/primer sequences are removed.

## When to Use This

- Processing Lexogen QuantSeq FWD/REV libraries
- Any 3' RNA-seq protocol with UMI + random primer structure
- Before aligning to reference genome for gene expression analysis

## Downstream Analysis

After processing with this cookbook:

1. **Align to reference genome** using STAR, HISAT2, or similar
2. **Assign to genes** using [mbf-bam-quantifier](https://tyberiusprime.github.io/mbf-bam-quantifier/), which also does UMI dedup
3. or **Deduplicate using UMI** with tools like:
   - `umi_tools dedup` (extracts UMI from comment)
   - `fgbio GroupReadsByUmi`
4. **Quantify differential gene expression** with standard DE tools (DESeq2, edgeR)

## Important Notes

- The 6bp random hexamer introduces sequence bias; UMI-based deduplication helps mitigate this
- QuantSeq reads are strand-specific (typically R2/reverse strand)
- Read lengths will be 14bp shorter after processing
- Quality filtering may be beneficial after trimming (see cookbook 03-quality-filtering)

## References

- [Lexogen QuantSeq 3' mRNA-Seq Library Prep Kit](https://www.lexogen.com/quantseq-3mrna-sequencing/)
",
        toml: r#"[input]
    # QuantSeq produces single-end reads
    read1 = 'input/quantseq_sample.fq'

[[step]]
    # Extract the 8bp UMI from the start of each read
    # QuantSeq uses 8bp random UMI for PCR duplicate identification
    action = 'ExtractRegions'
    out_label = 'umi'
    regions = [{ start = 0, length = 6, anchor="Start"}]
    source = 'read1'

[[step]]
    # Store the UMI in the FASTQ comment
    # This preserves it for downstream deduplication with umi_tools or similar
    action = 'StoreTagInComment'
    in_label = 'umi'

[[step]]
    # Remove the first 10 bases from reads:
    # - 6bp UMI
    # - 4bp TATA spacer
    # What remains is the actual cDNA sequence for alignment
    action = 'CutStart'
    segment = 'read1'
    n = 10

[output]
    prefix = "reference_output/output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"
"#,
    },
    Cookbook {
        number: 4,
        name: "04-phiX-removal",
        readme: r#"# Cookbook 04: PhiX Removal

## Use Case

You have Illumina PhiX spike-in sequences in your dataset and want to remove those contaminating reads before downstream analysis. PhiX is commonly added as a control to increase base diversity during sequencing runs.

## What This Pipeline Does

This cookbook demonstrates how to identify and remove PhiX contamination using k-mer counting:

1. **Count k-mers**: Uses `CalcKmers` to count how many 30-mers from each read match the PhiX genome
2. **Export data**: Saves k-mer counts to a TSV table for analysis
3. **Filter reads**: Removes reads with high PhiX k-mer counts (≥25 matching k-mers)

## Understanding the Approach

### K-mer Counting

The `CalcKmers` step counts how many k-mers (short subsequences of length k) from each read are present in the PhiX reference genome:

- **k = 30**: Uses 30-base-pair k-mers (longer k-mers = more specific matching)
- **canonical = true**: Counts both forward and reverse complement k-mers
- Reads stemming from PhiX will have many matching k-mers
- Clean reads will have very few or zero matching k-mers

### Analyzing the Data: Histogram and Threshold Selection

After running the initial pipeline with `StoreTagsInTable`,
examine the output TSV file to understand your data distribution:

```bash
# View the k-mer histogram with common command-line tools
# get second column, throw away header line, sort numerically, count unique occurrences
cut -f2 output_without_phix_kmer_analysis.tsv | tail -n +2 | sort -n | uniq -c

# alternativly, use awk for steps 1 & 2
awk 'NR>1 {print $2}' output_without_phix_kmer_analysis.tsv | sort -n | uniq -c
```

**Example output interpretation:**
```
  4   0    # 4 reads with 0 PhiX k-mers (clean reads)
  4  32    # 4 reads with 32 PhiX k-mers (PhiX contamination)
```

This bimodal distribution (two clear peaks) makes it easy to choose a threshold. Here, any value between 1-31 would work; we chose **25** as a conservative threshold.

**For larger datasets (first 1000 reads recommended):**
1. Run pipeline with `Head` step to sample reads: `[[step]]` with `action = "Head"` and `n = 1000`
2. Export the table and analyze the distribution in your preferred tool 
3. Look for a clear separation between clean and contaminated reads
4. Choose a threshold in the "valley" between peaks

## Filtering Approaches

This cookbook demonstrates three equivalent ways to filter PhiX-contaminated reads:

### Approach 1: FilterByNumericTag (Simplest, shown in input.toml)

```toml
[[step]]
    action = 'FilterByNumericTag'
    in_label = "phix_kmer_count"
    min_value = 25
    keep_or_remove = 'remove'  # Remove reads with ≥25 k-mers
```

**Best for:** Direct numeric filtering with a single threshold.

### Approach 2: EvalExpression + Demultiplex (Most Flexible)

```toml
# Create a boolean tag based on k-mer count threshold
[[step]]
    action = "EvalExpression"
    expression = "phix_kmer_count >= 25"
    out_label = "is_phix"
    result_type = "bool"

# Separate clean reads from PhiX-contaminated reads
# For boolean tags, Demultiplex creates files with pattern: {prefix}_{label}={value}_{segment}.fq
[[step]]
    action = "Demultiplex"
    in_label = "is_phix"

# No [barcodes] section needed for boolean demultiplexing!
# Output files will be:
# - output_is_phix=true_read1.fq  (PhiX-contaminated reads)
# - output_is_phix=false_read1.fq (clean reads)
```

**Best for:**
- Separating reads into multiple output files (contaminated vs. clean)
- Complex boolean expressions combining multiple criteria
- When you want to keep both categories for quality control


## Usage

### Using the Standard Approach (FilterByNumericTag)

```bash
# Run the pipeline
cd 04-phiX-removal
fastqrab input.toml

# Check the results
head output_without_phix_kmer_analysis.tsv      # View k-mer counts
grep -c "^@" output_without_phix_read1.fq       # Count output reads (should be 4)
```

### Using the Demultiplex Approach (Alternative)

To try the EvalExpression + Demultiplex approach that separates reads into two files:

```bash
# Run the alternative pipeline
fastqrab input_demultiplex.toml

# Check the results
head output_kmer_analysis.tsv                     # View k-mer counts
grep -c "^@" output_is_phix=false_read1.fq        # Count clean reads (should be 4)
grep -c "^@" output_is_phix=true_read1.fq         # Count PhiX reads (should be 4, have phiX in name.)
```

## Expected Results

With the provided sample data:
- **Input:** 8 reads (4 PhiX, 4 clean)
- **Output:** 4 clean reads (PhiX reads removed)
- **Table:** Shows k-mer counts for all input reads (32 for PhiX, 0 for clean)

## Customization

Adjust these parameters based on your data:
- **k**: Larger values (e.g., 35) = more specific; smaller values (e.g., 21) = more sensitive
- **min_count**: In `CalcKmers`, filters rare k-mers from the reference (default: 1)
- **threshold**: Adjust `min_value` in `FilterByNumericTag` based on your histogram analysis
"#,
        toml: r#"[input]
    read1 = 'input/phix_sample.fq'

[[step]]
    # Count k-mers matching the PhiX genome
    # Reads with many matching k-mers are likely PhiX contamination
    action = 'CalcKmers'
    out_label = 'phix_kmer_count'
    segment = 'read1'
    canonical = true  # Count both forward & reverse complement k-mers
    files = ["input/NC_001422.1.fasta"]
    k = 30

[[step]]
    # Export k-mer counts to TSV for histogram analysis
    action = 'StoreTagsInTable'
    infix = 'kmer_analysis'

[[step]]
    # Remove reads with ≥25 matching PhiX k-mers
    action = 'FilterByNumericTag'
    in_label = "phix_kmer_count"
    min_value = 25
    keep_or_remove = 'Remove'

[output]
    prefix = "reference_output_without_phix/output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"
"#,
    },
    Cookbook {
        number: 5,
        name: "05-quality-filtering",
        readme: r"# Cookbook 05: Quality Filtering

## Use Case

You have sequencing data with varying quality and want to remove low-quality reads before downstream analysis. Poor quality reads can introduce errors in variant calling, assembly, and other analyses.

## What This Pipeline Does

This cookbook demonstrates quality-based filtering using expected error calculation:

1. **Calculate Expected Errors**: Uses `CalcExpectedError` to compute the expected number of base call errors per read based on quality scores
2. **Filter Low-Quality Reads**: Uses `FilterByNumericTag` to remove reads exceeding an error threshold
3. **Generate Reports**: Creates quality reports before and after filtering to show improvement

## Understanding Expected Error

Expected error (EE) is a more nuanced quality metric than average quality score:

- **Formula**: EE = sum of error probabilities across all bases
- **Example**: A read with quality scores Q30, Q30, Q20, Q30 has EE ≈ 0.001 + 0.001 + 0.01 + 0.001 = 0.013
- **Interpretation**: Lower EE = higher confidence read
- **Threshold**: Common threshold is EE ≤ 1.0 (expect ≤1 error per read)

Quality scores and error probabilities:
- Q20 = 1% error rate (0.01 probability)
- Q30 = 0.1% error rate (0.001 probability)
- Q40 = 0.01% error rate (0.0001 probability)


## Expected Results

With the provided sample data:
- **Input:** 10 reads (5 high-quality, 5 low-quality)
- **Output:** 5 high-quality reads (low-quality reads removed)
- **Reports:** Before/after quality comparison showing improved quality metrics

## Customization

Adjust the filtering threshold based on your application:
- **Strict filtering (EE ≤ 0.5)**: For applications requiring highest accuracy (variant calling, metagenomics)
- **Standard filtering (EE ≤ 1.0)**: General-purpose filtering (shown in this cookbook)
- **Relaxed filtering (EE ≤ 2.0)**: When read depth is more important than individual read accuracy

You can also filter by other quality metrics:
- `CalcQualifiedBases`: Count bases above a quality threshold
- `FilterByNumericTag` with `min_value`: Keep reads with enough high-quality bases

## When to Use This

- After initial quality assessment (see Cookbook 01)
- Before alignment or assembly
- When downstream tools are sensitive to sequencing errors
- To reduce computational burden by removing unreliable data

## Downstream Analysis

After quality filtering:
1. **Alignment** to reference genome (BWA, Bowtie2, STAR)
2. **Variant calling** with higher confidence
3. **Assembly** with cleaner input data
4. **Quantification** with reduced noise
",
        toml: r#"[input]
    read1 = 'input/sample_R1.fq'

[[step]]
    # Generate initial quality report to assess data quality
    action = 'Report'
    name = 'initial'
    base_statistics = true

[[step]]
    # Calculate expected error (EE) for each read
    # EE = sum of error probabilities across all bases
    # Lower EE indicates higher quality reads
    action = 'CalcExpectedError'
    segment = 'read1'
    out_label = 'expected_error'
    aggregate = "max"

[[step]]
    # Filter reads based on expected error threshold
    # Keep only reads with EE ≤ 1.0 (expect ≤1 error per read)
    action = 'FilterByNumericTag'
    in_label = "expected_error"
    max_value = 1.0
    keep_or_remove = 'keep'

[[step]]
    # Generate report after filtering to show quality improvement
    action = 'Report'
    name = 'filtered'
    base_statistics = true

[output]
    prefix = "reference_output/output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"

[[step]]
    action = "OutputReport"
    json = false
    html = true
"#,
    },
    Cookbook {
        number: 6,
        name: "06-adapter-trimming",
        readme: r#"# Cookbook 06: Adapter Trimming with PolyA Tail Removal

## Use Case

You have RNA-seq data that contains:
- **PolyA tails**: Stretches of A bases at the 3' end (or polyT at 5' for reverse strand)
- **Sequencing adapters**: Illumina or other adapter sequences that need removal before alignment

These artifacts can interfere with alignment and downstream analysis if not removed.

## What This Pipeline Does

This cookbook demonstrates a complete adapter and polyA trimming workflow:

1. **Extract PolyA Tail**: Uses `ExtractPolyTail` to find polyA/T stretches
2. **Trim PolyA**: Uses `TrimAtTag` to remove the polyA tail and everything after it
3. **Extract Adapter**: Uses `ExtractIUPAC` to find Illumina adapter sequences
4. **Trim Adapter**: Uses `TrimAtTag` to remove adapter contamination
5. **Filter Short Reads**: Uses `CalcLength` and `FilterByNumericTag` to remove reads that became too short after trimming

## Understanding PolyA/T Tails

PolyA tails are natural features of mRNA:
- **Biological**: mRNA molecules have polyA tails added during transcription
- **Sequencing artifact**: If the read extends past the transcript end, it captures the polyA tail
- **Impact**: Can interfere with alignment if not removed
- **PolyT**: Reverse strand sequences show polyT instead of polyA


## Input Files

- `input/rna_sample_R1.fq` - RNA-seq reads with polyA tails and adapters

## Output Files

- `output_read1.fq` - Trimmed reads with polyA tails and adapters removed

## Expected Results

With the provided sample data:
- **Input:** 8 reads with various combinations of polyA tails and adapters
- **Output:** Trimmed reads with polyA and adapters removed
- Reads that became too short (< 25bp) after trimming are filtered out

## Workflow Details

**Example read transformation:**

Adapter
```
AGATCGGAAGAGC
```

**Before:**
```
@READ1
ACTGACTGACTGACTGAAAAAAAAAAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
              ^^^^^^^^^^^^^             
              PolyA ↑
                         ^^^^^^^^^^^^
                          Adapter ↑
```

**After polyA trimming:**
```
ACTGACTGACTGACTG
```

## Customization

Adjust parameters based on your data:

**PolyA Detection:**
- `min_length`: Minimum polyA length 
- `max_mismatch_rate`: Allow some misread (non-A) bases in the polyA tail

**Adapter Sequences:**

See [adapters sequences ]({{< relref "docs/reference/adapters.md" >}}) for common adapters.
- Use `max_mismatches` to allow for sequencing errors in adapter


**Length Filtering:**
- `min_value`: Minimum read length to keep (adjust based on alignment requirements)
- For RNA-seq: typically 25-50bp minimum
- For miRNA: might keep shorter reads (18-22bp)

## When to Use This

- RNA-seq data before alignment
- Any protocol where reads may extend past the insert (polyA capture)
- When adapter contamination is detected in quality reports
- Before transcriptome assembly or quantification

## Alternative Approaches

This cookbook uses a two-step approach (extract → trim). You can also use:
- `ExtractLongestPolyX`: Finds the longest stretch of any repeated nucleotide
- `ExtractAnchor`: More flexible pattern matching with orientation
- Multiple `TrimAtTag` steps for different adapter types

## Downstream Analysis

After trimming:
1. **Alignment** to reference genome (STAR, HISAT2)
2. **Quantification** of gene/transcript expression
3. **Quality control** to verify adapter removal (FastQC, MultiQC)
"#,
        toml: r#"[input]
    read1 = 'input/rna_sample_R1.fq'

[[step]]
    # Find polyA tails
    # Looks for stretches of ≥8 A's with up to 10% mismatches
    action = 'ExtractPolyTail'
    base = 'A'
    min_length = 8
    max_mismatch_rate = 0.1
    max_consecutive_mismatches = 3
    out_label = 'polya'

[[step]]
    # Trim the polyA tail and everything after it
    # keep_match = false means remove the matched region
    action = 'TrimAtTag'
    in_label = 'polya'
    keep_tag = false
    direction = 'end'

[[step]]
    # Find Illumina TruSeq Universal Adapter sequence
    # AGATCGGAAGAGC is the start of the Illumina adapter
    action = 'ExtractIUPAC'
    pattern = 'AGATCGGAAGAGC'
    anchor = "anywhere"
    max_mismatches = 1
    out_label = 'adapter'

[[step]]
    # Trim adapter and everything after it
    action = 'TrimAtTag'
    in_label = 'adapter'
    keep_tag = false
    direction = 'end'

[[step]]
    # Calculate read length after trimming
    action = 'CalcLength'
    segment = 'read1'
    out_label = 'length'

[[step]]
    # Filter out reads that are too short after trimming
    # Keep only reads ≥ 25bp
    action = 'FilterByNumericTag'
    in_label = 'length'
    min_value = 25
    keep_or_remove = 'keep'

[output]
    prefix = "reference_output/output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"
"#,
    },
    Cookbook {
        number: 7,
        name: "07-demultiplexing",
        readme: r#"# Cookbook 07: Demultiplexing by Inline Barcode

## Use Case

You have pooled sequencing data from multiple samples that were tagged with unique barcode sequences during library preparation
and have not been demuliplexed by your sequencing facility. 

You need to:
- Extract the barcode(s) from each read
- Correct sequencing errors in barcodes
- Separate reads into individual files per sample

This is common in multiplexed sequencing runs to maximize sequencing efficiency and reduce costs.

## What This Pipeline Does

This cookbook demonstrates a complete demultiplexing workflow:

1. **Extract Barcode**: Uses `ExtractRegion` to extract inline barcode from the start of reads (fixed position)
2. **Correct Errors**: Uses `HammingCorrect` to fix single-base errors in barcodes
3. **Remove Barcode from Sequence**: Uses `CutStart` to trim the barcode bases from reads
4. **Demultiplex**: Uses `Demultiplex` to split reads into separate files per sample
5. **Generate Report**: Creates summary statistics for each sample

## Understanding Barcodes

**Inline barcodes** are short DNA sequences (4-12bp) added to the start or end of reads:
- **Purpose**: Uniquely identify which sample each read came from
- **Location**: Typically at the 5' end of read1 or in a separate index read (we support any number of segments!)
- **Errors**: Sequencing errors can cause misassignment; error correction is helpful
- **Hamming distance**: Number of positions at which sequences differ
  - Hamming distance = 1: One base different (e.g., ATCG vs ACCG)
  - Good barcode sets have Hamming distance ≥ 3 for robust error correction

## Input Files

- `input/pooled_R1.fq` - Pooled reads from multiple samples with inline barcodes

## Output Files

- `output_sample1_read1.fq` - Reads belonging to sample1
- `output_sample2_read1.fq` - Reads belonging to sample2
- `output_sample3_read1.fq` - Reads belonging to sample3
- `output_sample4_read1.fq` - Reads belonging to sample4
- `output_no-barcode_read1.fq` - Reads with unrecognized barcodes

## Expected Results

With the provided sample data:
- **Input:** 12 reads (from 4 samples plus some with errors)
- **Output:** Separate files for each sample, with barcode sequences removed
- Barcodes with 1 error are corrected to the nearest valid barcode
- Reads with >1 error /no match go to the unmatched file

## Barcode Design Considerations

When designing barcodes:
1. **Hamming distance ≥ 3**: Allows single-error correction
2. **Balanced GC content**: Improves sequencing quality
3. **Avoid homopolymers**: AAAA, TTTT, etc. cause sequencing errors
4. **Distinct patterns**: Avoid similar-looking barcodes

**Example good barcode set (6bp, Hamming ≥ 3):**
- ATCACG
- CGATGT
- TTAGGC
- TGACCA
- ACAGTG
- GCCAAT

## Customization

Adjust parameters based on your experimental design:

**Barcode Location:**
Examples
- Start of read1: `segment = 'read1', start = 0, anchor='Start'`
- End of read1: `segment = 'read1', start = -6, anchor='End'` (for 6bp barcode)
- Separate index read: `segment = 'index1'`

**Error Correction:**
- `max_hamming_distance = 0`: No error correction, leave off the HammingCorrect step
- `max_hamming_distance = 1`: Correct single-base errors (recommended)
- `max_hamming_distance = 2`: Correct two errors (requires Hamming ≥ 5 barcode set)

**Unmatched Reads:**
- `output_unmatched = true`: Save unmatched reads for QC
- output_unmatched = false`: Discard unmatched reads
- `on_no_match = 'remove'`: Set tags that do not match to 'missing' (usefull for [FilterByTag]({{< relref "docs/reference/filter-steps/FilterByTag.md" >}})
- `on_no_match = 'empty'`: Set tags that do not match to "" (but keep the location data)
- `on_no_match = 'keep'`: Keep the non-matching barcode. Combine with 
[`tag_histogram in report]({{< relref "docs/reference/report-steps/Report.md" >}}) to 
find used-but-undocumented barcodes.

## When to Use This

- Multiplexed sequencing runs with inline barcodes
- Single-cell experiments with cell barcodes
- Pooled CRISPR screens with guide barcodes
- Any application where multiple samples are sequenced together

## Alternative Approaches

**Index reads instead of inline barcodes:**
If barcodes are in a separate index file rather than inline:
```toml
[[step]]
    action = 'ExtractRegion'
    segment = 'index1'  # Use index read instead
    start = 0
    length = 8
    out_label = 'barcode'
```

**Dual indexing:**
For higher multiplexing, use two index reads:
```toml
# Extract from index1
[[step]]
    action = 'ExtractRegion'
    segment = 'index1'
    start = 0
    length = 8
    out_label = 'i7'

# Extract from index2
[[step]]
    action = 'ExtractRegion'
    segment = 'index2'
    start = 0
    length = 8
    out_label = 'i5'

# Concatenate barcodes
[[step]]
    action = 'ConcatTags'
    in_labels = ['i7', 'i5']
    out_label = 'barcode'
    separator = '_'

# Then demultiplex on concatenated barcode
```

## Downstream Analysis

After demultiplexing:
1. **Quality control** per sample ([Report]({{< relref "docs/reference/report-steps/Report.md" >}}))
2. **Alignment** to reference genome
3. **Sample-specific analysis** (variant calling, expression quantification)
4. **Combine results** across samples for comparative analysis

## Quality Control

Check demultiplexing quality by examining:
- **Reads per sample**: Should be roughly balanced (unless intentionally unequal)
- **Unmatched rate**: High rates (>10%) suggest barcode design or sequencing issues
- **Error correction rate**: Monitor how many barcodes required correction
"#,
        toml: r#"[input]
    read1 = 'input/pooled_R1.fq'

[[step]]
    # Extract 6bp inline barcode from the start of read1
    action = 'ExtractRegion'
    segment = 'read1'
    start = 0
    length = 6
    out_label = 'barcode'
    anchor = "start"

[[step]]
    # Correct single-base sequencing errors in barcodes
    # max_hamming_distance = 1 allows correction of 1 mismatched base
    action = 'HammingCorrect'
    in_label = 'barcode'
    out_label = 'barcode_corrected'
    barcodes = 'sample_barcodes'
    max_hamming_distance = 1
    on_no_match = 'keep'  # Keep reads with unmatched barcodes
    on_tie = 'fail'

[[step]]
    # Remove the barcode sequence from the reads
    # This leaves only the biological sequence for alignment
    action = 'CutStart'
    segment = 'read1'
    n = 6

[[step]]
    # Split reads into separate files per sample
    # Creates output files: output_sample1_read1.fq, output_sample2_read1.fq, etc.
    action = 'Demultiplex'
    in_label = 'barcode_corrected'
    barcodes = 'sample_barcodes'
    output_unmatched = true  # Save unmatched reads to output_unmatched_read1.fq

# Define the barcode → sample mapping
# Barcode sequences are chosen to have Hamming distance ≥ 3
# This allows reliable single-error correction
[barcodes.sample_barcodes]
    ATCACG = 'sample1'
    CGATGT = 'sample2'
    TTAGGC = 'sample3'
    TGACCA = 'sample4'

[output]
    prefix = "reference_output/output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"
"#,
    },
    Cookbook {
        number: 8,
        name: "08-length-filtering",
        readme: r"# Cookbook 08: Read Length Filtering and Truncation

## Use Case

You have sequencing data with variable read lengths and need to:
- Remove reads that are too short (may align poorly or represent artifacts)
- Remove reads that are too long (may indicate technical issues)
- Truncate all reads to a uniform length (required by some downstream tools)

Read length filtering is important for:
- Quality control after adapter trimming
- Preparing data for tools that require uniform read lengths
- Removing degraded or artifactual sequences

## What This Pipeline Does

This cookbook demonstrates comprehensive read length management:

1. **Calculate Read Length**: Uses `CalcLength` to tag each read with its length
2. **Filter by Minimum Length**: Uses `FilterByNumericTag` to remove short reads
3. **Filter by Maximum Length**: Uses `FilterByNumericTag` to remove long reads
4. **Truncate to Uniform Length**: Uses `Truncate` to trim all reads to the same size
5. **Generate Reports**: Creates before/after statistics

## Understanding Read Length

**Why read length matters:**
- **Too short**: May align to multiple locations (multimapping)
- **Too long**: May indicate incomplete adapter trimming or concatenated sequences
- **Variable length**: Some tools (e.g., older aligners) require uniform lengths
- **Optimal range**: Depends on application (typically 25-150bp for RNA-seq)

**Common scenarios:**
- **After adapter trimming**: Reads become variable length; filter out very short ones
- **Amplicon sequencing**: Expected length range is tight (e.g., 250-280bp)
- **Small RNA**: Keep short reads (18-30bp) while filtering longer contamination
- **Assembly**: Longer reads generally better, but quality matters more


## Input Files

- `input/variable_length_R1.fq` - Reads with varying lengths (20-160bp)

## Output Files

- `output_read1.fq` - Reads filtered to 30-150bp range and truncated to 100bp

## Expected Results

With the provided sample data:
- **Input:** 10 reads with lengths ranging from 20 to 160bp
- **After min filter:** Removes reads < 30bp (e.g., 20bp, 25bp reads removed)
- **After max filter:** Removes reads > 150bp (e.g., 160bp read removed)
- **After truncate:** All remaining reads are exactly 100bp

## Workflow Details

**Example transformations:**

| Read ID | Original Length | After Min Filter | After Max Filter | After Truncate |
|---------|----------------|------------------|------------------|----------------|
| READ1   | 25bp          | Removed          | -                | -              |
| READ2   | 40bp          | Kept             | Kept             | → 40bp (kept) |
| READ3   | 100bp         | Kept             | Kept             | → 100bp       |
| READ4   | 120bp         | Kept             | Kept             | → 100bp       |
| READ5   | 160bp         | Kept             | Removed          | -              |

**Note on Truncate behavior:**
- If read is longer than target: trims to target length
- If read is shorter than target: keeps original length (does not pad)
- To enforce exact length, filter first: `min_value = target_length`

## Customization

Adjust parameters based on your application:

**RNA-seq (general):**
```toml
min_value = 25  # Minimum for reliable alignment
max_value = 200 # Filter abnormally long reads
# No truncation usually needed
```

**Amplicon sequencing (expected 250bp):**
```toml
min_value = 240  # Tight range around expected
max_value = 260
# Truncate to 250 for uniformity
```

**Small RNA-seq (miRNA):**
```toml
min_value = 18   # Shortest mature miRNA
max_value = 30   # Longest miRNA + some tolerance
# No truncation
```

**ChIP-seq or ATAC-seq:**
```toml
min_value = 25
max_value = 150
# Optional truncation to reduce file size
```

**Uniform length required:**
```toml
# First filter to ensure all reads are at least target length
min_value = 100
# Then truncate to exact length
[[step]]
    action = 'Truncate'
    segment = 'read1'
    length = 100
```

## When to Use This

- **After adapter trimming** to remove reads that became too short
- **Quality control** to filter abnormally long/short reads
- **Before tools** that require uniform read lengths
- **Amplicon analysis** to enforce expected size range
- **Small RNA analysis** to select specific size classes

## Alternative Approaches

**Using CutStart/CutEnd instead of Truncate:**
```toml
# Remove first 10bp and last 10bp
[[step]]
    action = 'CutStart'
    segment = 'read1'
    n = 10

[[step]]
    action = 'CutEnd'
    segment = 'read1'
    n = 10
```

**Filtering paired-end reads by combined length:**
```toml
# Calculate both read lengths
[[step]]
    action = 'CalcLength'
    segment = 'read1'
    out_label = 'len1'

[[step]]
    action = 'CalcLength'
    segment = 'read2'
    out_label = 'len2'

# Use EvalExpression to filter based on combined length
[[step]]
    action = 'EvalExpression'
    expression = 'len1 + len2 >= 50'
    out_label = 'long_enough'
    result_type = 'bool'

[[step]]
    action = 'FilterByTag'
    in_label = 'long_enough'
    keep_or_remove = 'keep'
```

## Downstream Analysis

After length filtering:
1. **Verify length distribution** with quality control tools (FastQC)
2. **Alignment** to reference genome (should have better mapping rates)
3. **Quantification** or other downstream analysis
4. **Compare** results with/without filtering to assess impact

## Quality Metrics

Monitor these metrics after length filtering:
- **Percentage reads retained**: Should retain most reads (>80% typical)
- **Mean read length**: Should match expected for your protocol
- **Mapping rate**: Often improves after filtering too-short reads
- **Alignment quality**: Fewer multimapping reads
",
        toml: r#"[input]
    read1 = 'input/variable_length_R1.fq'

[[step]]
    # Generate initial report to see input length distribution
    action = 'Report'
    name = 'initial'
  base_statistics = true

[[step]]
    # Calculate the length of each read and store in a tag
    action = 'CalcLength'
    segment = 'read1'
    out_label = 'length'

[[step]]
    # Remove reads shorter than 30bp
    # Short reads after adapter trimming often align poorly
    action = 'FilterByNumericTag'
    in_label = 'length'
    min_value = 30
    keep_or_remove = 'keep'

[[step]]
    # Remove reads longer than 150bp
    # Unusually long reads may indicate incomplete adapter trimming
    action = 'FilterByNumericTag'
    in_label = 'length'
    max_value = 150
    keep_or_remove = 'keep'


# Alternative filter both short and long reads at once
#[[step]]
  # # Remove reads shorter than 30bp
    # # Remove reads longer than 150bp
    # # Unusually long reads may indicate incomplete adapter trimming
    # action = 'FilterByNumericTag'
    # in_label = 'length'
    # min_value = 30
    # max_value = 150
    # keep_or_remove = 'keep'

[[step]]
    # Truncate all reads to exactly 100bp
    # Some downstream tools require uniform read lengths
    # Reads shorter than 100bp are kept at their original length
    action = 'Truncate'
    segment = 'read1'
    n = 100

[[step]]
    # Generate report after filtering and truncation
    action = 'Report'
    name = 'filtered'
    base_statistics = true

[output]
    prefix = "reference_output/output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"

[[step]]
    action = "OutputReport"
    json = false
    html = true
"#,
    },
    Cookbook {
        number: 9,
        name: "09-fastp-equivalent",
        readme: r#"# Cookbook 09: Fastp-Equivalent Workflow

## Use Case

You want to replicate the default behavior of [fastp](https://github.com/OpenGene/fastp/) — a popular all-in-one FASTQ preprocessor — using a configurable pipeline. This is useful when you need reproducible, step-by-step control over each filtering stage, or want to extend the workflow beyond what fastp offers.

## What This Pipeline Does

This cookbook replicates fastp's default single-end processing pipeline:

1. **PolyG Trimming**: Uses `ExtractPolyTail` + `TrimAtTag` to remove polyG tails (Illumina NextSeq/NovaSeq artifact)
2. **Adapter Trimming**: Uses `ExtractIUPAC` + `TrimAtTag` to remove the Illumina TruSeq R1 adapter
3. **N-base Filtering**: Uses `CalcNCount` + `FilterByNumericTag` to remove reads with too many ambiguous bases (`--n_base_limit 5`)
4. **Quality Filtering**: Uses `CalcQualifiedBases` + `FilterByNumericTag` to remove reads with too many low-quality bases (`--qualified_quality_phred 15`, `--unqualified_percent_limit 40`)
5. **Length Filtering**: Uses `CalcLength` + `FilterByNumericTag` to remove reads shorter than 15bp (`--length_required 15`)

## Fastp Defaults Replicated

| Fastp parameter | Value | Pipeline step |
|---|---|---|
| `--poly_g_min_len` | 10 | `ExtractPolyTail min_length = 10` |
| `--adapter_sequence` | `AGATCGGAAGAGCACACGTCTGAACTCCAGTCA` | `ExtractIUPAC query = ...` |
| `--n_base_limit` | 5 | `FilterByNumericTag max_value = 6` |
| `--qualified_quality_phred` | 15 (Phred) → 48 (ASCII) | `CalcQualifiedBases threshold = 48` |
| `--unqualified_percent_limit` | 40% → keep if ≥ 60% qualified | `FilterByNumericTag min_value = 0.60` |
| `--length_required` | 15 | `FilterByNumericTag min_value = 15` |

**Note on quality scores**: Quality values in FASTQ files are ASCII-encoded. Phred Q15 corresponds to ASCII character 48 (`15 + 33 = 48`).

## Fastp Considerations

**PolyG trimming** is automatically enabled in fastp when the read header starts with instrument prefixes indicating NextSeq or NovaSeq data (e.g., `@NS`, `@FS`, `@MN`, `@NB`, etc.). In this cookbook we enable it explicitly.

**Adapter detection** in fastp is automatic but requires several thousand reads. Here we specify the adapter sequence directly: `AGATCGGAAGAGCACACGTCTGAACTCCAGTCA` (Illumina TruSeq R1). See the [adapters reference]({{< relref "docs/reference/adapters.md" >}}) for other common sequences.

**Filtering order**: fastp applies trimming (polyG, adapter) before calculating quality metrics. This pipeline follows the same order.

## Input Files

- `R1.fq` — Single-end FASTQ reads

## Output Files

- `output_r1.fq` — Processed reads after all trimming and filtering steps

## Expected Results

With the provided sample data:
- Reads with polyG tails have tails removed
- Reads containing the TruSeq adapter are trimmed at the adapter site
- Reads with more than 5 N bases are removed
- Reads where fewer than 60% of bases meet Q15 are removed
- Reads shorter than 15bp (including those shortened by trimming) are removed

## Customization

**For paired-end data**, add `r2` to the input and apply matching steps to `segment = 'read2'`.

**Adapter sequences**: Replace the `query` value in the `ExtractIUPAC` step with your adapter. For common adapters see the [adapters reference]({{< relref "docs/reference/adapters.md" >}}).

**Stricter quality filtering:**
```toml
min_value = 0.80  # keep reads with ≥80% bases above threshold
```

**Longer minimum length** (e.g., for alignment):
```toml
min_value = 25
```

## When to Use This

- When you want to match fastp's default preprocessing for comparison or reproducibility
- As a starting point for custom workflows based on fastp's defaults
- When you need to inspect or audit each filtering step independently

## Downstream Analysis

After preprocessing:
1. **Alignment** to reference genome (BWA, STAR, Bowtie2)
2. **Quantification** of gene expression
3. **Variant calling** with improved accuracy from cleaner input data
"#,
        toml: r#"[input]
  r1 = 'R1.fq'



# equivalent to -g | --trim_poly_g
# first we must find out where they are
[[step]]
    action = "ExtractPolyTail"
    out_label = "polyG"
    min_length = 10 # --poly_g_min_len, default is 10 in fastp
    base = "G" 
    max_mismatch_rate = 0.125 # not configurable in fastp, but 1/8 is what it uses internally.
    max_consecutive_mismatches = 5 # not configurable in fastp

# then cut them off.
[[step]]
  action = 'TrimAtTag'
  in_label = 'polyG'
  direction ='end'
  keep_tag = false

# --adapter_sequence AGAT...
# ( auto detected in fastp after a a few thousand reads.) 
[[step]]
  action = 'ExtractIUPAC'
  out_label='adapter'
  query = "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  anchor = 'anywhere'
  max_mismatches = 5

[[step]]
  action = 'TrimAtTag'
  in_label = 'adapter'
  direction ='end'
  keep_tag = false

# fastp first cuts, then calculates the qualities!


# -- qualified_quality_phred  15
[[step]]
  action = 'CalcQualifiedBases'
  out_label = 'qual_base_rate'
  threshold = 48 # our qualities are in FASTQ-space, not in phred spacep
  operator = ">="
  relative = true # we want a rate.


[[step]]
  action = 'CalcNCount'
  out_label = 'n_count'
  relative = false

[[step]]
  action = 'FilterByNumericTag'
  max_value = 6
  keep_or_remove='keep'
  in_label = 'n_count'
 

[[step]]
  action = 'FilterByNumericTag'
  min_value = 0.60
  keep_or_remove='keep'
  in_label = 'qual_base_rate'
  

[[step]]
  action = 'CalcLength'
  out_label = 'length_r1'

[[step]]
  action = 'FilterByNumericTag'
  min_value = 15
  keep_or_remove='keep'
  in_label = 'length_r1'
 



[output]
    prefix = "output"

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputFASTQ"
"#,
    },
    Cookbook {
        number: 10,
        name: "10-adapter-identification",
        readme: r#"# Cookbook 10: Adapter Identification

## Use Case

You have a FASTQ file and want to identify which sequencing adapter is present
before trimming — or to confirm no adapter contamination remains after
trimming. This is useful when the adapter type is unknown, when working with
data from multiple library prep kits, or when validating a trimming step.

## What This Pipeline Does

1. Runs a single `Report` step that counts exact occurrences of each common
   adapter sequence in every read (`count_oligos`)
2. Writes an [HTML](./reference_output/output.html) and JSON report — no reads are filtered or written to disk

## How count_oligos Works

`count_oligos` performs exact, full-sequence matching across every read. A read
is counted if the probe sequence appears verbatim anywhere within it. There are
no mismatches and no IUPAC wildcards. A non-zero count means reads carry at
least one complete copy of that adapter.

Because the probe must appear in full, very short reads that were already
partially trimmed will *not* match. Use a shorter prefix of the adapter (e.g.
the first 15–20 bp) as an additional probe if you expect heavily trimmed data.

Every adapter is scored separately, so overlapping adapters are counted multiple times.

## Input Files

- `input/fastp_606.fq.gz` — Single-end reads containing the Illumina TruSeq Read 2 adapter

## Output Files

- `reference_output/output.report_adapter_check.html` — HTML report with oligo counts
- `reference_output/output.report_adapter_check.json` — JSON report with oligo counts

No FASTQ output is written (`format = 'None'`).

## Expected Results

With the provided sample data the report shows:

| Adapter | Count |
|---|---|
| `illumina_truseq_r2` | 1393 |
| all others | 0 |

This identifies the library as using the Illumina TruSeq Read 2 adapter (`AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT`).

## Next Steps

Once you have identified the adapter, add an `ExtractIUPAC` + `TrimAtTag` step to your pipeline. See [Cookbook 06: Adapter Trimming](../06-adapter-trimming) for a complete trimming example, and the [adapters reference]({{< relref "docs/reference/adapters.md" >}}) for copy/pastable `count_oligos` and `ExtractIUPAC` snippets.

## When to Use This

- Before trimming, to confirm which adapter is present
- After trimming, to verify that adapter contamination has been removed (counts should drop to zero)
- When processing data from an unknown or mixed source
"#,
        toml: r#"[input]
    read1 = 'input/fastp_606.fq.gz'

# Probe for common adapters using count_oligos.
# count_oligos performs exact full-sequence matching — no mismatches, no IUPAC.
# A count > 0 identifies reads that still carry adapter sequence.
# See the adapters reference for the full list of sequences.
[[step]]
    action = 'Report'
    name = 'adapter_check'
    count = true

    count_oligos = {
        # https://support-docs.illumina.com/SHARE/AdapterSequences/adapter-sequences.htm
        "Illumina Nextera/AmpliSeq"  = "CTGTCTCTTATACACATCT",
        "Illumina TruSeq R1/miRNA"   = "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
        "Illumina TruSeq R2"         = "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",

        # http://seqanswers.com/forums/showthread.php?t=87647 (2nd post)
        "BGI Forward"                = "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA",
        "BGI Reverse"                = "AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG",
    }

[output]
    prefix = 'reference_output/output'

# --- Output steps (migrated from [output]) ---
[[step]]
    action = "OutputReport"
    json = true
    html = true
"#,
    },
];

/// Get all cookbook names and their paths
#[must_use]
pub fn list_cookbooks() -> Vec<(usize, &'static str)> {
    COOKBOOKS.iter().map(|cb| (cb.number, cb.name)).collect()
}

/// Get a specific cookbook by number (1-indexed)
#[must_use]
pub fn get_cookbook(number: usize) -> Option<&'static Cookbook> {
    COOKBOOKS.iter().find(|cb| cb.number == number)
}

/// Get a specific cookbook by name
#[must_use]
pub fn get_cookbook_by_name(name: &str) -> Option<&'static Cookbook> {
    COOKBOOKS.iter().find(|cb| cb.name == name)
}
