[input]
    read1 = 'input_read1.fq'

[output]
    prefix = "output"

[[step]]
    action = 'CalcKmers'
    out_label = 'kmer_count_kmer_read_len'
    segment = 'read1'
    files = 'input_kmers.fa'
    k = 8
  # min_count = 1
    canonical = false

[[step]]
    action = 'StoreTagInComment'
    in_label = ['kmer_count_kmer_read_len']

[[step]]
    action = "OutputFASTQ"
