[package]
name = "fastqrab-io"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "FASTQ/FASTA/BAM input and output with gzip/zstd compression for fastqrab"
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[dependencies]
  anyhow = {workspace = true}
  bstr = {workspace = true}
  crossbeam = {workspace = true}
  ex = {workspace = true}
  fastqrab-config= {workspace = true}
  fastqrab-dna = {workspace = true}
  flate2 = {workspace = true}
  gzp = {workspace = true}
  hamming-resonate = {workspace = true}
  indexmap = {workspace = true}
  libc = {workspace = true}
  memchr = {workspace = true}
  mutants = {workspace = true}
  niffler = {workspace = true}
  noodles = {workspace = true}
  noodles-core = {workspace = true}
  schemars = {workspace = true}
  serde = {workspace = true}
  sha2 = {workspace = true}
  smallvec = {workspace = true}
  stringpod = {workspace = true}
  tempfile = {workspace = true}
  toml-pretty-deser = {workspace = true}
  zstd = {workspace = true}

[lints]
workspace = true
