#baseURL = 'https://tyberiusprime@github.io/pypipegraph2'
#canonifyURLs = true
locale = 'en-us'
title = 'fastqrab documentation'
theme = "hugo-book"
disablePathToLower = true

[params]
  BookRepo = 'https://github.com/TyberiusPrime/fastqrab'
  BookTheme = 'light'
