name: Build PR Binaries

env:
  PROJECT_NAME: fastqrab
  GITHUB_ACTIONS: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_binaries:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: ""
            use_target: false
            artifact_path: target/release
            bin_suffix: ""
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            use_target: true
            artifact_path: target/aarch64-apple-darwin/release
            bin_suffix: ""
          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            use_target: true
            artifact_path: target/x86_64-pc-windows-msvc/release
            bin_suffix: ".exe"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set COMMIT_HASH
        shell: bash
        run: echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e

      - name: Setup Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Setup WSL
        if: matrix.runner == 'windows-latest'
        uses: Vampire/setup-wsl@d1da7f2c0322a5ee4f24975344f67fc0f5baf364 # v7.0.0.
        with:
          distribution: Ubuntu-22.04

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Run Tests (Release)
        run: cargo test --verbose --locked --release
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3

      - name: Build Binary
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ matrix.use_target }}" == "true" ]]; then
            cargo build --verbose --locked --release --target ${{ matrix.target }}
          else
            cargo build --verbose --locked --release
          fi

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.name }}
          path: ${{ matrix.artifact_path }}/${{ env.PROJECT_NAME }}${{ matrix.bin_suffix }}
