[input]
    read1 = 'input_read1.fq.zst'
    read2 = 'input_read2.fq.zst'

[[step]]
    action = 'ExtractRegions'
    regions = [
            {  start = 6, length = 6, anchor='start'},
    ]
    source = 'read1'
    out_label = 'regs'

[[step]]
    action = 'ExtractRegions'
    regions = [
            {  start = 10, length = 7, anchor='Start'}
    ]
    source = 'read2'
    out_label = 'regs2'


[[step]]
  action = 'ConcatTags'
  in_labels = ['regs', 'regs2']
  out_label = 'regs_combo'
  on_missing = 'setmissing'
  separator = 'xyz'

[[step]]
    action = 'QuantifyTag'
    infix = 'kmer'
    in_label = 'regs_combo'

[output]
    prefix = 'output'
	compression = 'Zst'
